"""Persian -> canonical line-item mapping for Codal financial statements.

This is a restructured version of the old convert_to_en.py: same domain
knowledge (which Persian labels mean which line item), but as data (dicts)
instead of a few hundred `elif` branches, so it's easy to scan, extend, and
load into the `line_item_mapping` table. Labels not found here are ingested
with canonical_key=NULL and logged, instead of being silently dropped.
"""

# canonical_key -> English display label, shared across statement types.
CANONICAL_LABELS: dict[str, str] = {
    # --- Balance sheet ---
    "assets": "Assets",
    "no_trade_receivables": "No Trade Receivables",
    "no_trade_payables": "No Trade Payables",
    "noncurrent_advances_received": "Non-Current Advances Received",
    "noncurrent_assets": "Non-Current Assets",
    "tangible_fixed_assets": "Tangible Fixed Assets",
    "investment_in_properties": "Investment in Properties",
    "intangible_assets": "Intangible Assets",
    "longterm_investments": "Long-Term Investments",
    "longterm_receivables": "Long-Term Receivables",
    "tax_moved_assets": "Tax Moved Assets",
    "other_assets": "Other Assets",
    "total_noncurrent_assets": "Total Non-Current Assets",
    "current_assets": "Current Assets",
    "orders_and_prepayments": "Orders and Prepayments",
    "inventory": "Inventory",
    "trade_and_other_receivables": "Trade and Other Receivables",
    "shortterm_investments": "Short-Term Investments",
    "cash_and_equivalents": "Cash and Cash Equivalents",
    "assets_held_for_sale": "Assets Held for Sale",
    "total_current_assets": "Total Current Assets",
    "total_assets": "Total Assets",
    "equity_and_liabilities": "Equity and Liabilities",
    "equity": "Equity",
    "capital": "Capital",
    "capital_increase_in_progress": "Capital Increase in Progress",
    "share_premium": "Share Premium",
    "treasury_share_premium": "Treasury Share Premium",
    "legal_reserve": "Legal Reserve",
    "other_reserves": "Other Reserves",
    "revaluation_surplus": "Revaluation Surplus",
    "foreign_ops_exchange_diff": "Foreign Operations Exchange Differences",
    "retained_earnings": "Retained Earnings (Loss)",
    "treasury_shares": "Treasury Shares",
    "total_equity": "Total Equity",
    "liabilities": "Liabilities",
    "noncurrent_liabilities": "Non-Current Liabilities",
    "longterm_payables": "Long-Term Payables",
    "longterm_financial_facilities": "Long-Term Financial Facilities",
    "tax_moved_liabilities": "Tax Moved Liabilities",
    "employee_benefits_provision": "Employees End of Service Benefits Provision",
    "total_noncurrent_liabilities": "Total Non-Current Liabilities",
    "current_liabilities": "Current Liabilities",
    "trade_and_other_payables": "Trade and Other Payables",
    "tax_payable": "Tax Payable",
    "dividends_payable": "Dividends Payable",
    "shortterm_financial_facilities": "Short-Term Financial Facilities",
    "provisions": "Provisions",
    "advances_received": "Advances Received",
    "total_current_liabilities": "Total Current Liabilities",
    "total_liabilities": "Total Liabilities",
    "total_equity_and_liabilities": "Total Equity and Liabilities",
    "liabilities_related_to_assets_held_for_sale": "Liabilities Related to Assets Held for Sale",
    "revaluation_surplus_assets_held_for_sale": "Revaluation Surplus of Assets Held for Sale",
    "forex_reserve_govt_entities": "Foreign Operations Exchange Differences Reserve",
    "claims_from_banks": "Claims from Banks and Other Financial Institutions",
    "claims_from_government": "Claims from the Government",
    "loans_and_claims_govt_entities": "Loans Granted and Claims from Government Entities",
    "loans_and_claims_nongovt_entities": "Loans Granted and Claims from Non-Government Entities",
    "investment_in_securities": "Investments in Stocks and Other Securities",
    "claims_from_subsidiaries": "Claims from Subsidiary and Affiliated Companies",
    "other_receivable_accounts": "Other Receivable Accounts",
    "debt_to_banks": "Debt to Banks and Other Financial Institutions",
    "customer_deposits": "Customer Deposits",
    "debt_securities": "Debt Securities",
    "income_tax_reserve": "Income Tax Reserve",
    "reserves_and_other_liabilities": "Reserves and Other Liabilities",
    "employee_retirement_reserve": "Reserves for End-of-Service Benefits and Employee Retirement Commitments",
    "total_liabilities_before_deposit_equity": "Total Liabilities Before Shareholders' Equity of Investment Deposits",
    "deposit_holders_equity": "Shareholders' Equity of Investment Deposits",
    # --- Cash flow ---
    "operating_activities_header": "Operating Activities",
    "cash_generated_from_operations": "Cash Generated from Operations",
    "income_tax_paid": "Cash Payments for Income Taxes",
    "net_cash_operating": "Net Cash Provided by (Used in) Operating Activities",
    "investing_activities_header": "Cash Flows from Investing Activities",
    "proceeds_sale_tangible_assets": "Cash Receipts from Sale of Tangible Fixed Assets",
    "purchase_tangible_assets": "Cash Payments for Purchase of Tangible Fixed Assets",
    "proceeds_sale_held_for_sale_assets": "Cash Receipts from Sale of Held-for-Sale Assets",
    "proceeds_sale_intangible_assets": "Cash Receipts from Sale of Intangible Assets",
    "purchase_intangible_assets": "Cash Payments for Purchase of Intangible Assets",
    "proceeds_sale_longterm_investments": "Cash Receipts from Sale of Long-Term Investments",
    "purchase_longterm_investments": "Cash Payments for Long-Term Investments",
    "proceeds_sale_real_estate_investments": "Cash Receipts from Sale of Real Estate Investments",
    "purchase_real_estate_investments": "Cash Payments for Real Estate Investments",
    "proceeds_sale_shortterm_investments": "Cash Receipts from Sale of Short-Term Investments",
    "purchase_shortterm_investments": "Cash Payments for Short-Term Investments",
    "loans_granted_to_others": "Cash Payments for Loans Granted to Others",
    "repayment_loans_granted": "Cash Receipts from Repayment of Loans Granted to Others",
    "interest_income_loans_granted": "Cash Receipts from Interest on Loans Granted to Others",
    "dividend_income_received": "Cash Receipts from Dividend Income",
    "other_investment_income_received": "Cash Receipts from Other Investment Income",
    "net_cash_investing": "Net Cash Provided by (Used in) Investing Activities",
    "net_cash_before_financing": "Net Cash Before Financing Activities",
    "financing_activities_header": "Cash Flows from Financing Activities",
    "capital_contributions_received": "Cash Receipts from Capital Contributions",
    "proceeds_share_premium": "Cash Receipts from Share Premium",
    "proceeds_sale_treasury_shares": "Cash Receipts from Sale of Treasury Shares",
    "purchase_treasury_shares": "Cash Payments for Purchase of Treasury Shares",
    "proceeds_from_facilities": "Cash Receipts from Facilities",
    "repayment_facilities_principal": "Cash Payments for Principal of Facilities",
    "interest_paid_facilities": "Cash Payments for Interest on Facilities",
    "proceeds_participation_certificates": "Cash Receipts from Issuance of Participation Certificates",
    "repayment_participation_certificates": "Cash Payments for Principal of Participation Certificates",
    "interest_paid_participation_certificates": "Cash Payments for Interest on Participation Certificates",
    "proceeds_sukuk": "Cash Receipts from Issuance of Sukuk",
    "repayment_sukuk": "Cash Payments for Principal of Sukuk",
    "interest_paid_sukuk": "Cash Payments for Interest on Sukuk",
    "repayment_capital_lease": "Cash Payments for Principal of Capital Lease Installments",
    "interest_paid_capital_lease": "Cash Payments for Interest on Capital Lease",
    "dividends_paid": "Cash Payments for Dividends",
    "net_cash_financing": "Net Cash Provided by (Used in) Financing Activities",
    "net_increase_in_cash": "Net Increase (Decrease) in Cash Balance",
    "cash_beginning_balance": "Cash Balance at Beginning of Period",
    "fx_rate_effect": "Effects of Exchange Rate Changes",
    "cash_ending_balance": "Cash Balance at End of Period",
    "noncash_transactions": "Non-Cash Transactions",
    "net_cash_operating_ordinary": "Net Cash from Operating Activities - Ordinary",
    "net_cash_operating_extraordinary": "Net Cash from Operating Activities - Extraordinary",
    "investment_returns_and_financing_interest": "Investment Returns and Interest Paid for Financing",
    "net_cash_from_investment_returns_financing_interest": "Net Cash from Investment Returns and Interest Paid for Financing",
    # --- Income statement ---
    "net_profit": "Net Profit (Loss)",
    "operating_revenues": "Operating Revenues",
    "dividend_income": "Dividend Income",
    "guaranteed_profit_income": "Guaranteed Profit Income",
    "gain_loss_sale_investments": "Gain (Loss) from Sale of Investments",
    "gain_loss_fv_change_securities": "Gain (Loss) from Change in Fair Value of Securities",
    "other_operating_income": "Other Operating Income",
    "total_operating_revenues": "Total Operating Revenues",
    "operating_expenses": "Operating Expenses",
    "sga_expenses": "Selling, General, and Administrative Expenses",
    "other_operating_expenses": "Other Operating Expenses",
    "total_operating_expenses": "Total Operating Expenses",
    "operating_profit": "Operating Profit (Loss)",
    "financial_expenses": "Financial Expenses",
    "other_nonoperating_income_expenses": "Other Non-Operating Income and Expenses",
    "continuing_ops_profit_before_tax": "Continuing Operations Profit (Loss) Before Tax",
    "income_tax": "Income Tax",
    "net_income_continuing_ops": "Net Income (Loss) from Continuing Operations",
    "discontinued_ops_profit_after_tax": "Discontinued Operations Profit (Loss) After Tax",
    "basic_eps": "Basic Earnings (Loss) per Share",
    "basic_eps_continuing_operating": "Basic EPS from Continuing Operations - Operating",
    "basic_eps_continuing_nonoperating": "Basic EPS from Continuing Operations - Non-Operating",
    "basic_eps_discontinued": "Basic EPS from Discontinued Operations",
    "diluted_eps": "Diluted Earnings (Loss) per Share",
    "diluted_eps_continuing_operating": "Diluted EPS from Continuing Operations - Operating",
    "diluted_eps_continuing_nonoperating": "Diluted EPS from Continuing Operations - Non-Operating",
    "diluted_eps_discontinued": "Diluted EPS from Discontinued Operations",
    "retained_earnings_movement": "Retained Earnings (Loss) Movement",
    "retained_earnings_beginning": "Beginning Retained Earnings",
    "periodic_adjustments": "Periodic Adjustments",
    "retained_earnings_beginning_adjusted": "Adjusted Beginning Retained Earnings",
    "approved_dividend": "Approved Dividend",
    "capital_changes_from_retained_earnings": "Capital Changes from Retained Earnings",
    "unappropriated_retained_earnings_beginning": "Unappropriated Retained Earnings at Beginning of Period",
    "transfer_from_other_equity_items": "Transfer from Other Equity Items",
    "retained_earnings_available_for_allocation": "Retained Earnings Available for Allocation",
    "transfer_to_legal_reserve": "Transfer to Legal Reserve",
    "transfer_to_other_reserves": "Transfer to Other Reserves",
    "retained_earnings_ending": "Retained Earnings at End of Period",
    "net_eps_rial": "Net Earnings (Loss) per Share - Iranian Rials",
    "cost_of_goods_sold": "Cost of Goods Sold for Operating Income",
    "gross_profit": "Gross Profit (Loss)",
    "impairment_receivables": "Impairment of Receivables (Extraordinary Expense)",
    "other_income": "Other Income",
    "other_expenses": "Other Expenses",
    "other_nonoperating_misc": "Other Non-Operating Income - Miscellaneous Items",
    "current_year": "Current Year",
    "prior_years": "Prior Years",
    "discontinued_operations_header": "Discontinued Operations",
    "net_profit_discontinued_ops": "Net Profit (Loss) from Discontinued Operations",
    "operational_rial": "(Operational in Rials)",
    "nonoperational_rial": "(Non-operational in Rials)",
    "attributable_continuing_ops": "Attributable to Continuing Operations",
    "attributable_discontinued_ops": "Attributable to Discontinued Operations",
    "continuing_operations_header": "Continuing Operations",
    # --- Consolidated-statement-only additions (parent/NCI split, equity-method income) ---
    "minority_interest_net_income": "Net Income Attributable to Non-Controlling Interest",
    "minority_interest_retained_earnings": "Retained Earnings Attributable to Non-Controlling Interest",
    "net_income_attributable_parent": "Net Income Attributable to Parent Company Owners",
    "retained_earnings_attributable_parent": "Retained Earnings Attributable to Parent Company Owners",
    "share_of_associates_profit": "Share of Profit of Associates",
    "share_of_joint_ventures_profit": "Share of Profit of Joint Ventures",
    "profit_before_associates_share": "Profit Before Share of Associates' Profit",
    "attributable_to_header": "Attributable to:",
    "attributable_to_parent_label": "Owners of Parent Company",
    "attributable_to_nci_label": "Non-Controlling Interest",
    "payroll_expenses": "Payroll Expenses",
    "rent_expense": "Rent Expense",
    "depreciation_expense": "Depreciation Expense",
    "other_financing_nci": "Cash Flows from Non-Controlling Interest Transactions",
}

BALANCE_SHEET_MAP: dict[str, str] = {
    "دارایی‌ها": "assets", "دارايي‌ها": "assets", "دارایی‌‌ها": "assets", "دارایی ها": "assets",
    "دریافتنی‌‌های غیرتجاری": "no_trade_receivables",
    "پرداختنی‌های غیرتجاری": "no_trade_payables",
    "پیش‌دریافت‌های غیرجاری": "noncurrent_advances_received",
    "دارايی‌های غیرجاری": "noncurrent_assets", "دارایی‌‌های غیرجاری": "noncurrent_assets", "دارايي‌هاي غيرجاري": "noncurrent_assets",
    "دارایی‌های ثابت مشهود": "tangible_fixed_assets", "دارايي‌هاي ثابت مشهود": "tangible_fixed_assets", "دارایی‌هاي ثابت مشهود": "tangible_fixed_assets",
    "سرمایه‌گذاری در املاک": "investment_in_properties", "سرمايه‌گذاري در املاک": "investment_in_properties", "سرمایه گذاری در املاک": "investment_in_properties",
    "دارایی‌های نامشهود": "intangible_assets", "دارايي‌هاي نامشهود": "intangible_assets", "دارایی‌های نا مشهود": "intangible_assets", "دارایی‌هاي نا مشهود": "intangible_assets",
    "سرمایه‌گذاری‌های بلندمدت": "longterm_investments", "سرمايه‌گذاري‌هاي بلندمدت": "longterm_investments",
    "دریافتنی‌های بلندمدت": "longterm_receivables", "دریافتنی‌‌های بلندمدت": "longterm_receivables", "دريافتني‌هاي بلندمدت": "longterm_receivables",
    "دارايي ماليات انتقالي": "tax_moved_assets",
    "سایر دارایی‌ها": "other_assets", "ساير دارايي‌ها": "other_assets", "ساير دارایی‌ها": "other_assets",
    "جمع دارایی‌های غیرجاری": "total_noncurrent_assets", "جمع دارايي‌هاي غيرجاري": "total_noncurrent_assets",
    "دارایی‌های جاری": "current_assets", "دارایی‌‌های جاری": "current_assets", "دارايي‌هاي جاري": "current_assets",
    "سفارشات و پیش‌پرداخت‌ها": "orders_and_prepayments", "پیش پرداخت‌ها و سفارشات": "orders_and_prepayments", "سفارشات و پيش‌پرداخت‌ها": "orders_and_prepayments",
    "موجودی مواد و کالا": "inventory", "موجودي مواد و کالا": "inventory",
    "دریافتنی‌های تجاری و سایر دریافتنی‌ها": "trade_and_other_receivables", "دریافتنی‌‌های تجاری": "trade_and_other_receivables", "دريافتني‌هاي تجاري و ساير دريافتني‌ها": "trade_and_other_receivables",
    "سرمایه‌گذاری‌های کوتاه‌مدت": "shortterm_investments", "سرمایه‌گذاری‌‌های کوتاه مدت": "shortterm_investments", "سرمايه‌گذاري‌هاي کوتاه‌مدت": "shortterm_investments", "سرمایه‌گذاری‌‌های کوتاه‌مدت": "shortterm_investments",
    "موجودی نقد": "cash_and_equivalents", "موجودي نقد": "cash_and_equivalents",
    "دارایی‌های نگهداری شده برای فروش": "assets_held_for_sale", "دارايي‌هاي نگهداري شده براي فروش": "assets_held_for_sale",
    "جمع دارایی‌های جاری": "total_current_assets", "جمع دارايي‌هاي جاري": "total_current_assets",
    "جمع دارایی‌ها": "total_assets", "جمع دارايي‌ها": "total_assets",
    "حقوق مالکانه و بدهی‌ها": "equity_and_liabilities", "بدهی‌ها و حقوق صاحبان سهام": "equity_and_liabilities", "حقوق مالکانه و بدهي‌ها": "equity_and_liabilities",
    "حقوق مالکانه": "equity", "حقوق صاحبان سهام": "equity",
    "سرمايه": "capital", "سرمایه": "capital",
    "افزایش سرمایه در جریان": "capital_increase_in_progress", "افزایش (کاهش) سرمایه در جریان": "capital_increase_in_progress", "افزايش سرمايه در جريان": "capital_increase_in_progress",
    "صرف سهام": "share_premium", "صرف (کسر) سهام": "share_premium", "اندوخته صرف سهام": "share_premium",
    "صرف سهام خزانه": "treasury_share_premium",
    "اندوخته قانونی": "legal_reserve", "اندوخته قانوني": "legal_reserve", "سپرده قانونی": "legal_reserve",
    "ساير اندوخته‌ها": "other_reserves", "سایر اندوخته‌ها": "other_reserves",
    "مازاد تجدیدارزيابی دارایی‌ها": "revaluation_surplus", "مازاد تجدید ارزیابی دارایی‌ها": "revaluation_surplus", "مازاد تجديدارزيابي دارايي‌ها": "revaluation_surplus", "مازاد تجديد ارزيابي دارايي‌ها": "revaluation_surplus",
    "تفاوت تسعیر ارز عملیات خارجی": "foreign_ops_exchange_diff", "تفاوت تسعیر ناشی از تبدیل به واحد پول گزارشگری": "foreign_ops_exchange_diff", "تفاوت تسعير ارز عمليات خارجي": "foreign_ops_exchange_diff", "تفاوت تسعیر ارز": "foreign_ops_exchange_diff",
    "سود (زيان) انباشته": "retained_earnings", "سود (زیان) انباشته": "retained_earnings", "سود(زيان) انباشته": "retained_earnings",
    "سهام خزانه": "treasury_shares",
    "جمع حقوق مالکانه": "total_equity", "جمع حقوق صاحبان سهام": "total_equity",
    "بدهی‌ها": "liabilities", "بدهي‌ها": "liabilities",
    "بدهی‌های غیرجاری": "noncurrent_liabilities", "بدهي‌هاي غيرجاري": "noncurrent_liabilities",
    "پرداختنی‌های بلندمدت": "longterm_payables", "پرداختني‌هاي بلندمدت": "longterm_payables",
    "تسهیلات مالی بلندمدت": "longterm_financial_facilities", "تسهيلات مالي بلندمدت": "longterm_financial_facilities",
    "بدهي ماليات انتقالي": "tax_moved_liabilities",
    "ذخیره مزایای پایان خدمت کارکنان": "employee_benefits_provision", "ذخيره مزاياي پايان خدمت کارکنان": "employee_benefits_provision",
    "جمع بدهی‌های غیرجاری": "total_noncurrent_liabilities", "جمع بدهي‌هاي غيرجاري": "total_noncurrent_liabilities",
    "بدهی‌های جاری": "current_liabilities", "بدهي‌هاي جاري": "current_liabilities",
    "پرداختنی‌های تجاری و سایر پرداختنی‌ها": "trade_and_other_payables", "پرداختنی‌های تجاری": "trade_and_other_payables", "پرداختني‌هاي تجاري و ساير پرداختني‌ها": "trade_and_other_payables",
    "مالیات پرداختنی": "tax_payable", "ماليات پرداختني": "tax_payable",
    "سود سهام پرداختنی": "dividends_payable", "سود سهام پرداختني": "dividends_payable", "سود سهام پرداختی": "dividends_payable",
    "تسهیلات مالی": "shortterm_financial_facilities", "تسهيلات مالي": "shortterm_financial_facilities",
    "ذخایر": "provisions", "ذخاير": "provisions",
    "پیش‌دریافت‌ها": "advances_received", "پیش‌دریافت‌های جاری": "advances_received", "پيش‌دريافت‌ها": "advances_received",
    "جمع بدهی‌های جاری": "total_current_liabilities", "جمع بدهي‌هاي جاري": "total_current_liabilities",
    "جمع بدهی‌ها": "total_liabilities", "جمع بدهي‌ها": "total_liabilities", "جمع بدهی ها": "total_liabilities",
    "جمع حقوق مالکانه و بدهی‌ها": "total_equity_and_liabilities", "جمع بدهی‌ها و حقوق صاحبان سهام": "total_equity_and_liabilities", "جمع حقوق مالکانه و بدهي‌ها": "total_equity_and_liabilities", "جمع بدهي‌ها و حقوق مالکانه": "total_equity_and_liabilities", "جمع بدهی‌ها و حقوق مالکانه": "total_equity_and_liabilities",
    "بدهی‌های ‌مرتبط ‌با دارایی‌های نگهداری‌‌شده برای ‌فروش": "liabilities_related_to_assets_held_for_sale", "بدهی‌های مرتبط با دارایی‌های نگهداری شده برای فروش": "liabilities_related_to_assets_held_for_sale", "بدهي‌هاي ‌مرتبط ‌با دارايي‌هاي نگهداري‌‌شده براي ‌فروش": "liabilities_related_to_assets_held_for_sale",
    "مازاد تجدید ارزیابی دارایی‌های نگهداری شده برای فروش": "revaluation_surplus_assets_held_for_sale", "مازاد تجدید ارزیابی دارایی‌های غیرجاری نگهداری شده برای فروش": "revaluation_surplus_assets_held_for_sale",
    "اندوخته تسعیر ارز دارایی‌ها و بدهی‌های شرکت‌های دولتی": "forex_reserve_govt_entities", "اندوخته تسعير ارز دارايي‌ها و بدهي‌هاي شرکت‌هاي دولتي": "forex_reserve_govt_entities",
    "مطالبات از بانک ها و ساير موسسات اعتباري": "claims_from_banks",
    "مطالبات از دولت": "claims_from_government",
    "تسهيلات اعطايي و مطالبات از اشخاص دولتي": "loans_and_claims_govt_entities",
    "تسهيلات اعطايي و مطالبات از اشخاص غير دولتي": "loans_and_claims_nongovt_entities",
    "سرمایه‌گذاری در سهام و ساير اوراق بهادار": "investment_in_securities",
    "مطالبات از شرکت‌های فرعی و وابسته": "claims_from_subsidiaries",
    "ساير حسابهاي دريافتني": "other_receivable_accounts",
    "بدهي به بانكها و ساير موسسات اعتباري": "debt_to_banks",
    "سپرده‌هاي مشتریان": "customer_deposits",
    "اوراق بدهی": "debt_securities",
    "ذخيره ماليات عملکرد": "income_tax_reserve",
    "ذخاير و ساير بدهی‌ها": "reserves_and_other_liabilities",
    "ذخيره مزاياي پايان خدمت و تعهدات بازنشستگی کارکنان": "employee_retirement_reserve",
    "جمع بدهی های قبل از حقوق صاحبان سپرده های سرمایه گذاری": "total_liabilities_before_deposit_equity",
    "حقوق صاحبان سپرده‌های سرمایه‌گذاری": "deposit_holders_equity",
}

CASH_FLOW_MAP: dict[str, str] = {
    "جریان­‌های نقدی حاصل از فعالیت‌های عملیاتی:": "operating_activities_header", "جريان­هاي نقدي حاصل از فعاليت‌هاي عملياتي:": "operating_activities_header", "فعالیت‌های عملیاتی": "operating_activities_header", "جریان­های نقدی حاصل از فعاليت‌هاي عملياتي:": "operating_activities_header",
    "نقد حاصل از عملیات": "cash_generated_from_operations", "نقد حاصل از عمليات": "cash_generated_from_operations",
    "پرداخت‌های نقدی بابت مالیات بر درآمد": "income_tax_paid", "پرداخت‌هاي نقدي بابت ماليات بر درآمد": "income_tax_paid", "مالیات بر درآمد پرداختی": "income_tax_paid",
    "جریان ‌خالص ‌ورود‌ (خروج) ‌نقد حاصل از فعالیت‌های ‌عملیاتی": "net_cash_operating", "جريان ‌خالص ‌ورود‌ (خروج) ‌نقد حاصل از فعاليت‌هاي ‌عملياتي": "net_cash_operating", "جریان خالص ورود (خروج) وجه نقد ناشی از فعالیت‌های عملیاتی": "net_cash_operating",
    "جریان‌­های نقدی حاصل از فعالیت‌های سرمایه‌گذاری:": "investing_activities_header", "جريان­هاي نقدي حاصل از فعاليت‌هاي سرمايه‌گذاري:": "investing_activities_header", "جریان های نقدی حاصل از فعاليت‌هاي سرمايه‌گذاري:": "investing_activities_header", "فعالیت‌های سرمایه گذاری": "investing_activities_header", "فعاليت‌هاي سرمایه‌گذاری": "investing_activities_header",
    "دریافت‌های نقدی حاصل از فروش دارایی‌های ثابت مشهود": "proceeds_sale_tangible_assets", "دريافت‌هاي نقدي حاصل از فروش دارايي‌هاي ثابت مشهود": "proceeds_sale_tangible_assets", "دریافت‌های نقدی حاصل از فروش دارايي‌هاي ثابت مشهود": "proceeds_sale_tangible_assets", "وجوه دریافتی بابت فروش دارایی‌های ثابت مشهود": "proceeds_sale_tangible_assets", "وجوه دریافتی بابت فروش دارایی‌هاي ثابت مشهود": "proceeds_sale_tangible_assets",
    "پرداخت‌های نقدی برای خرید دارایی‌های ثابت مشهود": "purchase_tangible_assets", "پرداخت‌هاي نقدي براي خريد دارايي‌هاي ثابت مشهود": "purchase_tangible_assets", "پرداخت‌های نقدی برای خرید دارايي‌هاي ثابت مشهود": "purchase_tangible_assets", "وجوه پرداختی بابت خرید دارایی‌های ثابت مشهود": "purchase_tangible_assets", "وجوه پرداختي بابت تحصیل دارایی‌هاي ثابت مشهود": "purchase_tangible_assets",
    "دریافت‌های نقدی حاصل از فروش دارایی‌های نگهداری‌شده برای فروش": "proceeds_sale_held_for_sale_assets", "دريافت‌هاي نقدي حاصل از فروش دارايي‌هاي غيرجاري نگهداري‌شده براي فروش": "proceeds_sale_held_for_sale_assets", "دریافت‌های نقدی حاصل از فروش دارايي‌هاي غیرجاری نگهداری‌شده برای فروش": "proceeds_sale_held_for_sale_assets", "وجوه دریافتی بابت فروش دارایی‌های نگهداری شده برای فروش": "proceeds_sale_held_for_sale_assets",
    "دریافت‌های نقدی حاصل از فروش دارایی‌های نامشهود": "proceeds_sale_intangible_assets", "دريافت‌هاي نقدي حاصل از فروش دارايي‌هاي نامشهود": "proceeds_sale_intangible_assets", "دریافت‌های نقدی حاصل از فروش دارايي‌هاي ثابت نامشهود": "proceeds_sale_intangible_assets", "وجوه دریافتی بابت فروش دارایی‌های نامشهود": "proceeds_sale_intangible_assets", "وجوه دریافتی بابت فروش دارایی‌هاي نامشهود": "proceeds_sale_intangible_assets",
    "پرداخت‌های نقدی برای خرید دارایی‌های نامشهود": "purchase_intangible_assets", "پرداخت‌هاي نقدي براي خريد دارايي‌هاي نامشهود": "purchase_intangible_assets", "پرداخت‌های نقدی برای خرید دارايي‌هاي ثابت نامشهود": "purchase_intangible_assets", "وجوه پرداختی بابت خرید دارایی‌های نامشهود‌": "purchase_intangible_assets", "وجوه پرداختي بابت تحصیل دارایی‌هاي نامشهود": "purchase_intangible_assets",
    "دریافت‌های نقدی حاصل از فروش سرمايه‌گذاری‌های بلندمدت": "proceeds_sale_longterm_investments", "دريافت‌هاي نقدي حاصل از فروش سرمايه‌گذاري‌هاي بلندمدت": "proceeds_sale_longterm_investments", "دریافت های نقدی حاصل از فروش سرمایه گذاری بلند مدت": "proceeds_sale_longterm_investments", "وجوه دریافتی بابت فروش سرمایه‌گذاری‌های بلندمدت": "proceeds_sale_longterm_investments",
    "پرداخت‌های نقدی برای تحصیل سرمايه‌گذاری‌های بلندمدت": "purchase_longterm_investments", "پرداخت‌هاي نقدي براي تحصيل سرمايه‌گذاري‌هاي بلندمدت": "purchase_longterm_investments", "پرداخت های نقدی برای تحصیل سرمایه گذاری بلند مدت": "purchase_longterm_investments", "وجوه پرداختی بابت خرید سرمایه‌گذاری‌های بلندمدت": "purchase_longterm_investments",
    "دریافت‌های نقدی حاصل از فروش سرمایه‌گذاری در املاک": "proceeds_sale_real_estate_investments", "دريافت‌هاي نقدي حاصل از فروش سرمايه‌گذاري در املاک": "proceeds_sale_real_estate_investments", "دریافت های نقدی حاصل از فروش سرمایه گذاری در املاک": "proceeds_sale_real_estate_investments", "وجوه دریافتی بابت فروش سرمایه‌گذاری‌ در املاک": "proceeds_sale_real_estate_investments", "وجوه دریافتی بابت فروش املاک و مستغلات غیر عملیاتی": "proceeds_sale_real_estate_investments",
    "پرداخت‌های نقدی برای تحصیل سرمایه‌گذاری در املاک": "purchase_real_estate_investments", "پرداخت‌هاي نقدي براي تحصيل سرمايه‌گذاري‌ در املاک": "purchase_real_estate_investments", "پرداخت های نقدی برای تحصیل سرمایه گذاری در املاک": "purchase_real_estate_investments", "وجوه پرداختی بابت خرید سرمایه‌گذاری در املاک": "purchase_real_estate_investments", "وجوه پرداختي بابت تحصیل املاک و مستغلات غیر عملیاتی": "purchase_real_estate_investments",
    "دریافت‌های نقدی حاصل از فروش سرمايه‌گذاری‌های کوتاه‌مدت": "proceeds_sale_shortterm_investments", "دريافت‌هاي نقدي حاصل از فروش سرمايه‌گذاري‌هاي کوتاه‌مدت": "proceeds_sale_shortterm_investments", "دریافت های نقدی حاصل از فروش سرمایه گذاری کوتاه مدت": "proceeds_sale_shortterm_investments", "وجوه دریافتی بابت فروش سرمایه‌گذاری‌های کوتاه‌مدت": "proceeds_sale_shortterm_investments",
    "پرداخت‌های نقدی برای تحصیل سرمایه‌گذاری‌های کوتاه‌مدت": "purchase_shortterm_investments", "پرداخت‌هاي نقدي براي تحصيل سرمايه‌گذاري‌هاي کوتاه‌مدت": "purchase_shortterm_investments", "پرداخت های نقدی برای تحصیل سرمایه گذاری کوتاه مدت": "purchase_shortterm_investments", "وجوه پرداختی بابت خرید سرمایه‌گذاری‌های کوتاه‌مدت": "purchase_shortterm_investments",
    "پرداخت های نقدی بابت تسهیلات اعطایی به دیگران": "loans_granted_to_others", "پرداخت‌هاي نقدي بابت تسهيلات اعطايي به ديگران": "loans_granted_to_others", "پرداخت های نقدی برای تسهیلات اعطایی به دیگران": "loans_granted_to_others", "تسهیلات اعطایی به اشخاص": "loans_granted_to_others",
    "دریافت‌های نقدی حاصل از استرداد تسهیلات اعطایی به دیگران": "repayment_loans_granted", "دريافت‌هاي نقدي حاصل از استرداد تسهيلات اعطايي به ديگران": "repayment_loans_granted", "دریافت های نقدی حاصل از استرداد تسهیلات اعطایی به دیگران": "repayment_loans_granted", "استرداد تسهیلات اعطایی به اشخاص": "repayment_loans_granted",
    "دریافت‌های نقدی حاصل از سود تسهیلات اعطایی به دیگران": "interest_income_loans_granted", "دريافت‌هاي نقدي حاصل از سود تسهيلات اعطايي به ديگران": "interest_income_loans_granted", "دریافت های نقدی حاصل از سود تسهیلات اعطایی به دیگران": "interest_income_loans_granted",
    "دریافت‌های نقدی حاصل از سود‌ سهام": "dividend_income_received", "دريافت‌هاي نقدي حاصل از سود‌ سهام": "dividend_income_received", "دریافت های نقدی حاصل از سود سهام": "dividend_income_received",
    "دریافت‌های نقدی حاصل از سود سایر سرمایه‌گذاری‌ها": "other_investment_income_received", "دريافت‌هاي نقدي حاصل از سود ساير سرمايه‌گذاري‌ها": "other_investment_income_received", "دریافت های نقدی حاصل از سود سرمایه گذاری ها": "other_investment_income_received", "سود دریافتی بابت سایر سرمایه‌گذاری‌ها": "other_investment_income_received",
    "جريان خالص ورود (خروج) نقد حاصل از فعاليت‌های سرمایه‌گذاری": "net_cash_investing", "جريان خالص ورود (خروج) نقد حاصل از فعاليت‌هاي سرمايه‌گذاري": "net_cash_investing", "جریان خالص ورود (خروج) وجه نقد ناشی از فعالیت‌های سرمایه‌گذاری": "net_cash_investing", "جريان خالص ورود (خروج) وجه نقد ناشی از فعاليت‌هاي سرمایه‌گذاری": "net_cash_investing",
    "جريان خالص ورود (خروج) نقد قبل از فعالیت‌های تامین مالی": "net_cash_before_financing", "جريان خالص ورود (خروج) نقد قبل از فعاليت‌هاي تامين مالي": "net_cash_before_financing", "جریان خالص ورود (خروج) وجه نقد قبل از فعالیت‌های تأمین مالی": "net_cash_before_financing", "جريان خالص ورود (خروج) وجه نقد قبل از فعالیت‌های تامین مالی": "net_cash_before_financing",
    "جریان­‌های نقدی حاصل از فعالیت‌های تامین مالی:": "financing_activities_header", "جريان­هاي نقدي حاصل از فعاليت‌هاي تامين مالي:": "financing_activities_header", "جریان های نقدی حاصل از فعاليت‌هاي تامين مالي:": "financing_activities_header", "فعالیت‌های تأمین مالی": "financing_activities_header", "فعاليت‌هاي تأمين مالي": "financing_activities_header",
    "دریافت‌های نقدی حاصل از افزايش سرمايه": "capital_contributions_received", "دريافت‌هاي نقدي حاصل از افزايش سرمايه": "capital_contributions_received", "وجوه دریافتی حاصل از افزایش سرمایه": "capital_contributions_received",
    "دریافت‌های نقدی حاصل از صرف سهام": "proceeds_share_premium", "دريافت‌هاي نقدي حاصل از صرف سهام": "proceeds_share_premium",
    "دریافت‌های نقدی حاصل از فروش سهام خزانه": "proceeds_sale_treasury_shares", "دريافت‌هاي نقدي حاصل از فروش سهام خزانه": "proceeds_sale_treasury_shares", "وجوه دریافتی حاصل از فروش سهام خزانه": "proceeds_sale_treasury_shares", "وجوه دریافتی بابت فروش سهام خزانه": "proceeds_sale_treasury_shares",
    "پرداخت‌های نقدی برای خرید سهام خزانه": "purchase_treasury_shares", "پرداخت‌هاي نقدي براي خريد سهام خزانه": "purchase_treasury_shares", "وجوه پرداختی بابت خرید سهام خزانه": "purchase_treasury_shares",
    "دریافت‌های نقدی حاصل از تسهيلات": "proceeds_from_facilities", "دريافت‌هاي نقدي حاصل از تسهيلات": "proceeds_from_facilities", "وجوه دریافتی حاصل از استقراض": "proceeds_from_facilities",
    "پرداخت‌های نقدی بابت اصل تسهيلات": "repayment_facilities_principal", "پرداخت‌هاي نقدي بابت اصل تسهيلات": "repayment_facilities_principal", "بازپرداخت اصل استقراض": "repayment_facilities_principal",
    "پرداخت‌های نقدی بابت سود تسهيلات": "interest_paid_facilities", "پرداخت‌هاي نقدي بابت سود تسهيلات": "interest_paid_facilities", "سود پرداختی بابت استقراض": "interest_paid_facilities",
    "دریافت‌های نقدی حاصل از انتشار اوراق مشارکت": "proceeds_participation_certificates", "دريافت‌هاي نقدي حاصل از انتشار اوراق مشارکت": "proceeds_participation_certificates",
    "پرداخت‌های نقدی بابت اصل اوراق مشارکت": "repayment_participation_certificates", "پرداخت‌هاي نقدي بابت اصل اوراق مشارکت": "repayment_participation_certificates",
    "پرداخت‌های نقدی بابت سود اوراق مشارکت": "interest_paid_participation_certificates", "پرداخت‌هاي نقدي بابت سود اوراق مشارکت": "interest_paid_participation_certificates",
    "دریافت‌های نقدی حاصل از انتشار اوراق خرید دین": "proceeds_sukuk", "دريافت‌هاي نقدي حاصل از انتشار اوراق خريد دين": "proceeds_sukuk",
    "پرداخت‌های نقدی بابت اصل اوراق خرید دین": "repayment_sukuk", "پرداخت‌هاي نقدي بابت اصل اوراق خريد دين": "repayment_sukuk",
    "پرداخت‌های نقدی بابت سود اوراق خرید دین": "interest_paid_sukuk", "پرداخت‌هاي نقدي بابت سود اوراق خريد دين": "interest_paid_sukuk",
    "پرداخت‌های نقدی بابت اصل اقساط اجاره سرمایه‌ای": "repayment_capital_lease", "پرداخت‌هاي نقدي بابت اصل اقساط اجاره سرمايه‌اي": "repayment_capital_lease",
    "پرداخت‌های نقدی بابت سود اجاره سرمایه‌ای": "interest_paid_capital_lease", "پرداخت‌هاي نقدي بابت سود اجاره سرمايه‌اي": "interest_paid_capital_lease",
    "پرداخت‌های نقدی بابت سود سهام": "dividends_paid", "پرداخت‌هاي نقدي بابت سود سهام": "dividends_paid", "سود سهام پرداختی": "dividends_paid",
    "جريان خالص ورود (خروج) نقد حاصل از فعالیت‌های تامين مالی": "net_cash_financing", "جريان خالص ورود (خروج) نقد حاصل از فعاليت‌هاي تامين مالي": "net_cash_financing", "جریان خالص ورود (خروج) وجه نقد ناشی از فعالیت‌های تأمین مالی": "net_cash_financing",
    "خالص افزايش (کاهش) در موجودی نقد": "net_increase_in_cash", "خالص افزايش (کاهش) در موجودي نقد": "net_increase_in_cash", "خالص افزایش (کاهش) در موجودی نقد": "net_increase_in_cash",
    "مانده موجودی نقد در ابتدای سال": "cash_beginning_balance", "مانده موجودي نقد در ابتداي سال": "cash_beginning_balance", "موجودی نقد در ابتدای دوره": "cash_beginning_balance",
    "تاثير تغييرات نرخ ارز": "fx_rate_effect", "تآثیر تغییرات نرخ ارز": "fx_rate_effect",
    "مانده موجودي نقد در پايان سال": "cash_ending_balance", "مانده موجودی نقد در پايان سال": "cash_ending_balance", "مانده موجودی نقد در پايان دوره": "cash_ending_balance", "موجودی نقد در پایان دوره": "cash_ending_balance",
    "معاملات غیرنقدی": "noncash_transactions", "معاملات غيرنقدي": "noncash_transactions", "مبادلات غیرنقدی": "noncash_transactions",
    "جریان خالص ورود (خروج) وجه نقد ناشی از فعالیت‌های عملیاتی - عادی": "net_cash_operating_ordinary",
    "جریان خالص ورود (خروج) وجه نقد ناشی از فعالیت‌های عملیاتی - استثنایی": "net_cash_operating_extraordinary",
    "بازده سرمایه‌گذاری‌ها و سود پرداختی بابت تأمین مالی": "investment_returns_and_financing_interest",
    "جریان خالص ورود (خروج) وجه نقد ناشی از بازده سرمایه‌گذاری‌ها و سود پرداختی بابت تأمین مالی": "net_cash_from_investment_returns_financing_interest",
    # --- Consolidated-statement variants ---
    "پرداخت‌های نقدی بابت اصل اوراق بدهی (صکوک، اجاره، مشارکت و ...)": "repayment_sukuk",
    "پرداخت‌های نقدی بابت تسهیلات اعطایی به دیگران": "loans_granted_to_others",
    "پرداخت‌های نقدی بابت سود اوراق بدهی (صکوک، اجاره، مشارکت و ...)": "interest_paid_sukuk",
    "پرداخت‌های نقدی بابت سود سهام به مالکان شرکت اصلی": "dividends_paid",
    "پرداخت‌های نقدی بابت سود سهام به منافع فاقد حق کنترل": "dividends_paid",
    "پرداخت‌های نقدی برای تحصیل سایر سرمايه‌گذاري‌هاي بلندمدت": "purchase_longterm_investments",
    "پرداخت‌های نقدی برای تحصیل سرمايه‌گذاري‌ در املاک": "purchase_real_estate_investments",
    "پرداخت‌های نقدی برای تحصیل سرمايه‌گذاري‌هاي کوتاه‌مدت": "purchase_shortterm_investments",
    "پرداخت‌های نقدی برای تحصیل سرمایه‌گذاری‌ در املاک": "purchase_real_estate_investments",
    "پرداخت‌های نقدی برای تحصیل سرمایه‌گذاری‌های بلندمدت": "purchase_longterm_investments",
    "پرداخت‌های نقدی برای خرید دارايي‌هاي نامشهود": "purchase_intangible_assets",
    "پرداخت‌های نقدی برای خرید سرمایه‌گذاری در شرکت‌های وابسته": "purchase_longterm_investments",
    "پرداخت‌های نقدی برای خرید سرمایه‌گذاری در شرکت‌های وابسته و مشارکت‌های خاص": "purchase_longterm_investments",
    "پرداخت‌های نقدی برای خرید شرکت‌های فرعی پس از کسر وجوه نقد تحصیل شده": "purchase_longterm_investments",
    "پرداخت‌های نقدی ناشی از تحصیل منافع فاقد حق کنترل": "other_financing_nci",
    "پرداخت‌های نقدی ناشی از خرید سهام خزانه توسط شرکت فرعی- سهم منافع فاقد حق کنترل": "purchase_treasury_shares",
}

INCOME_STATEMENT_MAP: dict[str, str] = {
    "سود (زیان) خالص": "net_profit",
    "درآمدهای عملیاتی": "operating_revenues",
    "درآمد سود سهام": "dividend_income",
    "درآمد سود تضمین شده": "guaranteed_profit_income",
    "سود (زیان) فروش سرمایه گذاری ها": "gain_loss_sale_investments",
    "سود (زیان) تغییر ارزش سرمایه گذاری در اوراق بهادار": "gain_loss_fv_change_securities",
    "سایر درآمدهای عملیاتی": "other_operating_income",
    "جمع درآمدهای عملیاتی": "total_operating_revenues",
    "هزینه های عملیاتی": "operating_expenses",
    "هزینه‌های فروش، اداری و عمومی": "sga_expenses", "هزينه‏‌هاى فروش، ادارى و عمومى": "sga_expenses",
    "سایر هزینه‌های عملیاتی": "other_operating_expenses",
    "جمع هزینه های عملیاتی": "total_operating_expenses",
    "سود (زیان) عملیاتی": "operating_profit", "سود (زيان) عملياتي": "operating_profit",
    "هزینه‌های مالی": "financial_expenses", "هزينه‏‌هاى مالى": "financial_expenses",
    "سایر درآمدها و هزینه‌های غیرعملیاتی": "other_nonoperating_income_expenses", "سایر درآمدها و هزینه‌های غیرعملیاتی- درآمد سرمایه‌گذاری‌ها": "other_nonoperating_income_expenses",
    "سود (زیان) عملیات در حال تداوم قبل از مالیات": "continuing_ops_profit_before_tax", "سود (زيان) عمليات در حال تداوم قبل از ماليات": "continuing_ops_profit_before_tax",
    "مالیات بر درآمد": "income_tax", "هزینه مالیات بر درآمد:": "income_tax",
    "سود (زیان) خالص عملیات در حال تداوم": "net_income_continuing_ops", "سود (زيان) خالص عمليات در حال تداوم": "net_income_continuing_ops",
    "سود (زیان) عملیات متوقف ‌شده پس از اثر مالیاتی": "discontinued_ops_profit_after_tax",
    "سود (زیان) پایه هر سهم ناشی از عملیات در حال تداوم- عملیاتی": "basic_eps_continuing_operating",
    "سود (زیان) پایه هر سهم ناشی از عملیات در حال تداوم- غیرعملیاتی": "basic_eps_continuing_nonoperating",
    "سود (زیان) پایه هر سهم ناشی از عملیات متوقف ‌شده": "basic_eps_discontinued", "سود (زیان) پایه هر سهم ناشی از عملیات متوقف‌ شده": "basic_eps_discontinued", "سود (زیان) تقلیل یافته هر سهم ناشی از عملیات متوقف ‌شده": "basic_eps_discontinued",
    "سود (زیان) پایه هر سهم": "basic_eps", "سود (زيان) پايه هر سهم": "basic_eps",
    "سود (زیان) تقلیل یافته هر سهم": "diluted_eps",
    "سود (زیان) تقلیل یافته هر سهم ناشی از عملیات در حال تداوم- عملیاتی": "diluted_eps_continuing_operating",
    "سود (زیان) تقلیل یافته هر سهم ناشی از عملیات در حال تداوم- غیرعملیاتی": "diluted_eps_continuing_nonoperating",
    "سود (زیان) تقلیل یافته هر سهم ناشی از عملیات متوقف‌ شده": "diluted_eps_discontinued",
    "گردش حساب سود (زیان) انباشته": "retained_earnings_movement",
    "سود (زیان) انباشته ابتدای دوره": "retained_earnings_beginning",
    "تعدیلات سنواتی": "periodic_adjustments",
    "سود (زیان) انباشته ابتدای دوره تعدیل‌شده": "retained_earnings_beginning_adjusted", "سود (زیان) انباشته ابتدای دوره تعدیل ‌شده": "retained_earnings_beginning_adjusted",
    "سود سهام‌ مصوب": "approved_dividend",
    "تغییرات سرمایه از محل سود (زیان) انباشته": "capital_changes_from_retained_earnings",
    "سود (زیان) انباشته ابتدای دوره تخصیص نیافته": "unappropriated_retained_earnings_beginning",
    "انتقال از سایر اقلام حقوق صاحبان سهام": "transfer_from_other_equity_items",
    "سود قابل تخصیص": "retained_earnings_available_for_allocation",
    "انتقال به اندوخته‌ قانوني‌": "transfer_to_legal_reserve",
    "انتقال به سایر اندوخته‌ها": "transfer_to_other_reserves",
    "سود (زیان) انباشته‌ پايان‌ دوره": "retained_earnings_ending",
    "سود (زیان) خالص هر سهم- ریال": "net_eps_rial", "سود (زیان) خالص هر سهم– ریال": "net_eps_rial",
    "سرمایه": "capital",
    "بهاى تمام شده درآمدهای عملیاتی": "cost_of_goods_sold", "بهای تمام ‌شده درآمدهای عملیاتی": "cost_of_goods_sold",
    "سود (زيان) ناخالص": "gross_profit", "سود (زیان) ناخالص": "gross_profit",
    "هزینه کاهش ارزش دریافتنی‌‏ها (هزینه استثنایی)": "impairment_receivables",
    "ساير درآمدها": "other_income",
    "سایر هزینه‌ها": "other_expenses",
    "سایر درآمدها و هزینه‌های غیرعملیاتی- اقلام متفرقه": "other_nonoperating_misc",
    "سال جاری": "current_year",
    "سال‌های قبل": "prior_years",
    "عملیات متوقف شده:": "discontinued_operations_header",
    "سود (زیان) خالص عملیات متوقف شده": "net_profit_discontinued_ops",
    "عملیاتی (ریال)": "operational_rial",
    "غیرعملیاتی (ریال)": "nonoperational_rial",
    "ناشی از عملیات در حال تداوم": "attributable_continuing_ops",
    "ناشی از عملیات متوقف شده": "attributable_discontinued_ops",
    "عملیات در حال تداوم:": "continuing_operations_header",
    # --- Consolidated-statement variants (parent/NCI split, equity-method income, spelling variants) ---
    "زیان کاهش ارزش دریافتنی‌ها": "impairment_receivables",
    "ساير درآمدها و هزينه ‏هاى غيرعملياتى": "other_nonoperating_income_expenses",
    "سهم اقلیت از سود (زیان) انباشته": "minority_interest_retained_earnings",
    "سهم اقلیت از سود (زیان) خالص": "minority_interest_net_income",
    "سهم گروه از سود شرکت‌های وابسته": "share_of_associates_profit",
    "سهم گروه از سود مشارکت­هاي خاص": "share_of_joint_ventures_profit",
    "سود (زيان) خالص": "net_profit",
    "سود (زيان) قبل از احتساب سهم گروه از سود شرکت‌هاي وابسته": "profit_before_associates_share",
    "سود (زیان) قبل از احتساب سهم گروه از سود شرکت‌های وابسته": "profit_before_associates_share",
    "سود (زیان) قبل از احتساب سهم گروه از سود شرکت‌های وابسته و مشارکت­های خاص": "profit_before_associates_share",
    "سود (زیان) انباشته‌ قابل انتساب به صاحبان سهام شرکت اصلی": "retained_earnings_attributable_parent",
    "سود (زیان) تغییر ارزش سرمایه گذاریها": "gain_loss_fv_change_securities",
    "سود (زیان) خالص قابل انتساب به صاحبان سهام شرکت اصلی": "net_income_attributable_parent",
    "سود (زیان) خالص هر سهم (ریال)": "net_eps_rial",
    "سود (زیان) عملياتى": "operating_profit",
    "سود (زیان) عملیات در حال تداوم قبل از ماليات": "continuing_ops_profit_before_tax",
    "سود (زیان) فروش سرمایه گذاریها": "gain_loss_sale_investments",
    "سود (زیان) پایه هر سهم (ریال)": "basic_eps",
    "سود (زیان) پایه هر سهم قابل انتساب به مالکان شرکت اصلی:": "basic_eps",
    "سود (زیان) پایه هر سهم:": "basic_eps",
    "قابل انتساب به:": "attributable_to_header",
    "مالکان شرکت اصلی": "attributable_to_parent_label",
    "منافع فاقد حق کنترل": "attributable_to_nci_label",
    "ناشی از عملیات در حال تداوم (ریال)": "attributable_continuing_ops",
    "ناشی از عملیات متوقف شده (ریال)": "attributable_discontinued_ops",
    "هزينه ‏هاى حقوق، دستمزد و مزایا": "payroll_expenses",
    "هزينه‌هاى فروش، ادارى و عمومى": "sga_expenses",
    "هزينه‏ هاى فروش، ادارى و عمومى": "sga_expenses",
    "هزينه‏ هاى مالى": "financial_expenses",
    "هزینه اجاره": "rent_expense",
    "هزینه استهلاک": "depreciation_expense",
    "هزینه کاهش ارزش دریافتنی ‏ها (هزینه استثنایی)": "impairment_receivables",
    "گردش حساب سود (زیان) انباشته تلفیقی": "retained_earnings_movement",
}

MAPS_BY_STATEMENT_TYPE: dict[str, dict[str, str]] = {
    "balance_sheet": BALANCE_SHEET_MAP,
    "cash_flow": CASH_FLOW_MAP,
    "income_statement": INCOME_STATEMENT_MAP,
}


def canonical_key_for(label_fa: str, statement_type: str) -> str | None:
    """Look up the canonical key for a Persian label within a statement type."""
    return MAPS_BY_STATEMENT_TYPE[statement_type].get(label_fa.strip())
